name: Push to master

on:
  push:
    branches:
      - ci-xml-files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add secret token
      with:
        token: ${{secrets.API_TOKEN_GITHUB_PUSH_TO_REPO}}
    - name: Add sync ci-xml-files branch to master
      run: |
          mv ./ xml
          git checkout master
          git merge ci-xml-files
