name: merge schema branch to master
on:
  push:
    branches: [ci-schema-files]
    paths:
      - "schemas/**"
jobs:
  merge-ci-schema-files-back-to-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Ensure master branch is up-to-date
        run: |
          git fetch --unshallow
          git checkout master
          git pull origin master
      - name: Merge ci-schema-files into master
        run: |
          git merge --no-ff --allow-unrelated-histories ci-schema-files -m "Auto-merge ci-schema-files back to master"
      - name: Push changes to master
        run: |
          git push origin master
      - name: Delete ci-schema-files branch
        if: success()
        run: |
          git push origin --delete ci-schema-files
      - name: Clean up local repository
        run: |
          git branch -D ci-schema-files
